#ifndef RENDERERTERRAINCOMMON_H_INCLUDED
#define RENDERERTERRAINCOMMON_H_INCLUDED

#define TERRAIN_PATCH_SIZE				121
#define TERRAIN_SPLAT_TEXTURE_DIMENSION	2048

#endif // RENDERERTERRAINCOMMON_H_INCLUDED
